DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	first_name VARCHAR(80) NOT NULL,
	last_name VARCHAR(80) NOT NULL,
	address_street VARCHAR(80) NOT NULL,
	address_no VARCHAR(80) NOT NULL,
	city VARCHAR(80) NOT NULL,
	country VARCHAR(80) NOT NULL,
	postal_code VARCHAR(80) NOT NULL,
	created_at VARCHAR(255) NOT NULL
	);